// Generated from public Wikimedia/Wikidata sources.
window.__TEP_PLAYER_PHOTOS__=Object.freeze({
  "alexander zverev": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2f/Alexander_Zverev.jpg/330px-Alexander_Zverev.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  "anna blinkova": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/86/Day_6_-_Transilvania_Open_Anna_Blinkova_%28cropped%29.jpg/330px-Day_6_-_Transilvania_Open_Anna_Blinkova_%28cropped%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  "anna pushkareva": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/76/Anna_Pushkareva_25May24_0306.jpg/330px-Anna_Pushkareva_25May24_0306.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  "aryna sabalenka": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/57/Aryna_Sabalenka_Miami_Open_Final.jpg/330px-Aryna_Sabalenka_Miami_Open_Final.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  "ben shelton": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1b/Ben_Shelton%2C_media_conference%2C_Swiss_Indoors_Basel_2025_%28cropped%29.jpg/330px-Ben_Shelton%2C_media_conference%2C_Swiss_Indoors_Basel_2025_%28cropped%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  "claire liu": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/18/Claire_Liu_%282026_US_Open%29_01_%28cropped%29.jpg/330px-Claire_Liu_%282026_US_Open%29_01_%28cropped%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  "diede de groot": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/18/25th_Laureus_World_Sports_Awards_-_Red_Carpet_-_Diede_de_Groot_-_240422_184135_%28cropped%29.jpg/330px-25th_Laureus_World_Sports_Awards_-_Red_Carpet_-_Diede_de_Groot_-_240422_184135_%28cropped%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  "elena rybakina": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d3/Elena_Rybakina_%282025_DC_Open%29_11_%28cropped%29.jpg/330px-Elena_Rybakina_%282025_DC_Open%29_11_%28cropped%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  "elsa jacquemot": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8d/Elsa_Jacquemot_%282023_US_Open%29_09_%28cropped%29.jpg/330px-Elsa_Jacquemot_%282023_US_Open%29_09_%28cropped%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  "fiona ferro": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/06/Ferro_RG19_%2810%29_%2848199369072%29.jpg/330px-Ferro_RG19_%2810%29_%2848199369072%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  "frances tiafoe": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a3/FrancesTiafo.jpg/330px-FrancesTiafo.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  "juan pablo varillas": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/dd/Varillas_WMQ22_%2810%29.jpg/330px-Varillas_WMQ22_%2810%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  "karen khachanov": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/df/Karen_Khachanov_%282024_DC_Open%29_02.jpg/330px-Karen_Khachanov_%282024_DC_Open%29_02.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  "leolia jeanjean": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d8/Jeanjean_WMQ23_%2853061887794%29.jpg/330px-Jeanjean_WMQ23_%2853061887794%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  "niels vink": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/49/Niels_Vink_Paris_2024.jpg/330px-Niels_Vink_Paris_2024.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  "thiago seyboth wild": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/75/Thiago_Seyboth_Wild_-_2024_Olympics_%28cropped%29.jpg/330px-Thiago_Seyboth_Wild_-_2024_Olympics_%28cropped%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail"
});
