import {allocate,activeOpportunities,age,number,norm,POLICY} from './surebet-core.mjs';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(v),pct=v=>`${(v*100).toLocaleString('it-IT',{minimumFractionDigits:2,maximumFractionDigits:2})}%`,odd=v=>number(v)>1?number(v).toFixed(2).replace('.',','):'—';
const old=v=>age(v)>POLICY.maxAge,elapsed=v=>Number.isFinite(age(v))?`${Math.floor(age(v))} min`:'data assente';
const labels={MATCH_WINNER_2WAY:'Vincente match',TOTAL_GAMES_2WAY:'Totale game',GAME_HANDICAP_2WAY:'Handicap game'};
const reasons={COPERTURA_INSUFFICIENTE:'Disponibile un solo bookmaker',MARGINE_TROPPO_BASSO:'Margine insufficiente',QUOTA_NON_FRESCA:'Quote da aggiornare',QUOTE_NON_SINCRONE:'Aggiornamenti troppo distanti',QUOTA_OUTLIER:'Quote discordanti',BUFFER_NON_SUPERATO:'Margine assorbito dagli arrotondamenti e dal buffer',FINESTRA_ESECUZIONE_TROPPO_CORTA:'Tempo residuo insufficiente',EVENTO_NON_PREMATCH:'Evento iniziato o concluso'};
let board=null,offline=false,busy=false,limit=12,shown=[],lastOps='';
function cardTitle(r){return `<div class="arbTitle">${esc(r.player_a)} <span class="muted">vs</span> ${esc(r.player_b)}</div><p class="meta">${esc(r.tournament)} · ${esc(labels[r.market]||r.market)}${r.line!=null?' · '+esc(r.line):''}</p>`}
function renderOps(){
 const ops=activeOpportunities(board),signature=JSON.stringify(ops.map(x=>[x.event_id,x.market_key,x.expires_at,x.odds_a,x.odds_b]));
 if(signature!==lastOps||!$('list').innerHTML){lastOps=signature;$('list').innerHTML=ops.length?ops.map((r,i)=>`<article class="arb">${cardTitle(r)}<div class="legs"><div class="leg"><strong>${esc(r.selection_a||r.player_a)}</strong><b>${odd(r.odds_a)}</b><span>${esc(r.book_a)}</span></div><div class="leg"><strong>${esc(r.selection_b||r.player_b)}</strong><b>${odd(r.odds_b)}</b><span>${esc(r.book_b)}</span></div></div><p class="positive">Margine teorico ${pct(r.raw_roi)} · <span data-expiry="${esc(r.expires_at)}"></span></p><button class="btn" data-op="${i}">Calcola la ripartizione</button></article>`).join(''):'<div class="empty">Nessuna opportunità attiva. Puoi confrontare i dati disponibili o inserire le tue quote nel calcolatore.</div>';
 $('list').querySelectorAll('[data-op]').forEach(b=>b.onclick=()=>{const original=ops[Number(b.dataset.op)],current=activeOpportunities(board).find(r=>r.event_id===original.event_id&&r.market_key===original.market_key&&r.expires_at===original.expires_at);if(current)prefill(current)});
 }
 document.querySelectorAll('[data-expiry]').forEach(el=>el.textContent=`scade tra ${Math.max(0,Math.floor((Date.parse(el.dataset.expiry)-Date.now())/1000))} s`);
 const m=board?.meta||{},stale=old(m.updated_at),ready=m.status==='READY'&&!stale;
 $('kActive').textContent=ops.length;$('kCompared').textContent=m.events_compared??new Set((board?.checked||[]).filter(r=>r.market_depth>=2).map(r=>r.event_id)).size;$('kBooks').textContent=m.bookmaker_count??'—';$('kAge').textContent=elapsed(m.updated_at);
 $('headline').textContent=ops.length?`${ops.length} opportunità attive`:offline?'Feed non disponibile':!board?'Le quote, a confronto.':!ready?'Quote da aggiornare':Number($('kCompared').textContent)===0?'Copertura insufficiente':'Le quote, a confronto.';
 $('feedState').textContent=offline?'Non disponibile':m.status==='API_PAUSA'?'Budget gratuito in pausa':m.status==='SETUP'?'Feed da configurare':m.status==='ERROR'?'Errore del feed':stale?'Report da aggiornare':'Report disponibile';$('feedState').className=`status ${ready?'good':'warn'}`;
 $('heroSub').textContent=ops.length?'Combinazioni che superano i controlli sulle quote. Verifica sempre accettazione e regolamenti.':offline?'Non posso verificare le opportunità. Il calcolatore manuale rimane disponibile.':!ready?'Nessun segnale attivo viene mantenuto con dati non verificabili. Usa il confronto come riferimento o inserisci quote aggiornate.':'Non tutte le partite hanno due bookmaker o quote abbastanza recenti. Qui puoi vedere cosa è stato davvero confrontato.';
 $('coverage').textContent=board?`${m.events_with_quotes??new Set((board.checked||[]).map(r=>r.event_id)).size} match con quote · ${m.events_total??'—'} nel radar · ${m.events_scanned??0} richiesti nell’ultima scansione.`:'';
 $('budgetInfo').textContent=m.shared_requests_24h!=null?`Richieste registrate nelle ultime 24 ore: ${m.shared_requests_24h} / ${m.shared_budget_24h}. Questa elaborazione: ${m.api_calls??0} chiamate. Le quote condivise non richiedono chiamate aggiuntive.`:'';
}
function renderComparison(){
 const q=norm($('search').value),market=$('market').value,rows=(board?.checked||[]).filter(r=>(!market||r.market===market)&&norm(`${r.player_a} ${r.player_b} ${r.tournament}`).includes(q));shown=rows.slice(0,limit);
 $('compareCount').textContent=`${rows.length} mercati disponibili · ${Math.min(limit,rows.length)} visualizzati. L’età è quella della quota, non del report.`;
 $('comparison').innerHTML=shown.map((r,i)=>{const quotes=r.quotes||[{book:r.book_a,a:r.odds_a,updated_at:r.updated_a},{book:r.book_b,b:r.odds_b,updated_at:r.updated_b}].filter(x=>x.book);const fresh=r.book_a&&r.book_b&&!old(r.updated_a)&&!old(r.updated_b)&&Date.parse(r.start_at)>Date.now();return `<article class="arb">${cardTitle(r)}<div class="quotegrid muted"><span>Bookmaker</span><span>${esc(r.selection_a||r.player_a)}</span><span>${esc(r.selection_b||r.player_b)}</span></div>${quotes.map(x=>`<div class="quotegrid"><span>${esc(x.book)}<small>${old(x.updated_at)?'Da aggiornare · ':''}${elapsed(x.updated_at)}</small></span><strong class="${old(x.updated_at)?'old':''}">${odd(x.a)}</strong><strong class="${old(x.updated_at)?'old':''}">${odd(x.b)}</strong></div>`).join('')}<p class="helper">${esc((r.reasons||[]).map(x=>reasons[x]||x).join(' · ')||'Controlli sulle quote superati al momento del report')}${Date.parse(r.start_at)<=Date.now()?' · Partita iniziata':''}</p>${fresh?`<button class="btn" data-compare="${i}">Usa le due quote nel calcolatore</button>`:''}</article>`}).join('')||'<div class="empty">Nessuna quota disponibile per questa ricerca. Il calcolatore manuale non dipende dalla copertura del feed.</div>';
 $('more').hidden=limit>=rows.length;$('comparison').querySelectorAll('[data-compare]').forEach(b=>b.onclick=()=>{const r=shown[Number(b.dataset.compare)];if(!old(r.updated_a)&&!old(r.updated_b)&&Date.parse(r.start_at)>Date.now())prefill(r);else renderComparison()});
}
function prefill(r){$('qa').value=r.odds_a;$('qb').value=r.odds_b;$('rules').checked=false;$('manualContext').textContent=`${r.selection_a||r.player_a} (${r.book_a}) / ${r.selection_b||r.player_b} (${r.book_b}) · quote copiate dal report: ricontrollale.`;renderCalc();$('manual').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});$('qa').focus({preventScroll:true})}
function renderCalc(){const a=allocate($('bankroll').value,$('qa').value,$('qb').value,$('cost').value);if(!a){$('manualResult').innerHTML='<p class="muted">Inserisci due quote da 1,01 a 1000, un totale da 2 a 1.000.000 € e costi non superiori alle puntate. Sono accettate virgola e punto.</p>';return}
 const positive=a.profit>0;$('manualResult').innerHTML=`<p class="${positive?'positive':'negative'}"><strong>${positive?'Margine matematico positivo':'Nessun profitto nei due scenari'}: ${money(a.profit)} (${pct(a.roi)})</strong></p><div class="calc"><div class="calcBox"><b>${money(a.sa)}</b><span>Puntata esito A</span></div><div class="calcBox"><b>${money(a.sb)}</b><span>Puntata esito B</span></div><div class="calcBox"><b>${money(a.profitA)}</b><span>Saldo se vince A</span></div><div class="calcBox"><b>${money(a.profitB)}</b><span>Saldo se vince B</span></div></div><p class="helper">Totale puntate ${money(a.spent)} + costi ${money(a.cost)}. Ritorni arrotondati per difetto al centesimo.</p><div class="guard">${$('rules').checked?'Conferma inserita da te. Il calcolo non verifica quote, regolamenti o accettazione presso i bookmaker.':'Simulazione: prima di considerare questa copertura, verifica evento, esiti e regole nella casella sopra.'}</div>`;
}
async function load(){if(busy)return;busy=true;$('refresh').disabled=true;$('refresh').textContent='Aggiornamento…';try{const r=await fetch(`./data/surebet-board.json?v=${Date.now()}`,{cache:'no-store',signal:AbortSignal.timeout(12000)});if(!r.ok)throw new Error('FEED');const next=await r.json();if(!next.meta||!Array.isArray(next.checked)||!Array.isArray(next.opportunities))throw new Error('FORMAT');board=next;offline=false}catch{board=null;offline=true}finally{busy=false;$('refresh').disabled=false;$('refresh').textContent='↻ Aggiorna';renderOps();renderComparison()}}
$('refresh').onclick=load;for(const id of ['qa','qb','bankroll','cost','rules'])$(id).addEventListener('input',()=>{if(id==='qa'||id==='qb'){$('rules').checked=false;$('manualContext').textContent='Quote modificate manualmente · verifica di nuovo evento e regolamento.'}renderCalc()});
for(const id of ['search','market'])$(id).addEventListener('input',()=>{limit=12;renderComparison()});$('more').onclick=()=>{limit+=12;renderComparison()};$('resetCalc').onclick=()=>{$('qa').value='';$('qb').value='';$('rules').checked=false;$('manualContext').textContent='Dati inseriti da te.';renderCalc();$('qa').focus()};
renderCalc();load();setInterval(renderOps,1000);setInterval(load,30000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)load()});
