import fs from 'node:fs';
const file=process.argv[2]||'data/surebet-board.json';
const x=JSON.parse(fs.readFileSync(file,'utf8'));
const errors=[],seen=new Set();
if(!x||typeof x!=='object')errors.push('BOARD_MISSING');
if(!x.meta||typeof x.meta!=='object')errors.push('META_MISSING');
if(!Array.isArray(x.opportunities))errors.push('OPPORTUNITIES_INVALID');
if(x.meta?.fail_closed!==true&&x.meta?.status==='READY')errors.push('FAIL_CLOSED_OFF');
const boardAt=new Date(x.meta?.updated_at||0).getTime();
const maxAge=Math.max(1,Number(x.meta?.max_quote_age_min)||10);
const maxSpread=Math.max(1,Number(x.meta?.max_timestamp_spread_min)||5);
const minRaw=Math.max(0,Number(x.meta?.min_raw_roi)||0);
const minWindow=Math.max(0,Number(x.meta?.min_execution_window_sec)||0);
for(const r of x.opportunities||[]){
  const id=String(r.event_id||'NO_ID');
  if(seen.has(id))errors.push(`DUPLICATE:${id}`);seen.add(id);
  if(r.status!=='SUREBET')errors.push(`STATUS:${id}`);
  if(r.market!=='MATCH_WINNER_2WAY')errors.push(`MARKET:${id}`);
  if(r.same_market_verified!==true)errors.push(`MARKET_VERIFY:${id}`);
  if(r.certainty_scope!=='MATHEMATICAL_ODDS_ONLY')errors.push(`CERTAINTY_SCOPE:${id}`);
  if(!Array.isArray(r.reasons)||r.reasons.length)errors.push(`REASONS:${id}`);
  if(!(Number(r.odds_a)>1&&Number(r.odds_b)>1))errors.push(`ODDS:${id}`);
  if(!r.book_a||!r.book_b||r.book_a===r.book_b)errors.push(`BOOKS:${id}`);
  const s=1/Number(r.odds_a)+1/Number(r.odds_b),roi=1/s-1;
  if(!(s<1))errors.push(`NOT_ARB:${id}`);
  if(!(Number(r.raw_roi)>=minRaw&&Number(r.raw_roi)>0))errors.push(`ROI:${id}`);
  if(!(Number(r.buffered_roi)>0))errors.push(`BUFFER:${id}`);
  const ta=new Date(r.updated_a||0).getTime(),tb=new Date(r.updated_b||0).getTime(),exp=new Date(r.expires_at||0).getTime();
  if(!(Number.isFinite(ta)&&Number.isFinite(tb)&&ta>0&&tb>0))errors.push(`TIMESTAMP:${id}`);
  if(Number.isFinite(boardAt)&&boardAt>0&&((boardAt-ta)/60000>maxAge+.05||(boardAt-tb)/60000>maxAge+.05))errors.push(`STALE:${id}`);
  if(Math.abs(ta-tb)/60000>maxSpread+.05)errors.push(`SPREAD:${id}`);
  if(!(Number.isFinite(exp)&&exp>boardAt))errors.push(`EXPIRY:${id}`);
  if(Number.isFinite(exp)&&Number.isFinite(boardAt)&&(exp-boardAt)/1000+1<minWindow)errors.push(`WINDOW:${id}`);
  if(!r.stake_100||Math.abs(Number(r.stake_100.stake_a)+Number(r.stake_100.stake_b)-100)>.02)errors.push(`STAKE:${id}`);
  const worst=Math.min(Number(r.stake_100.stake_a)*Number(r.odds_a),Number(r.stake_100.stake_b)*Number(r.odds_b));
  if(!(worst>100))errors.push(`ROUNDING:${id}`);
  if(Math.abs(Number(r.stake_100.worst_return)-worst)>.03)errors.push(`WORST_RETURN:${id}`);
}
if((x.opportunities||[]).length&&x.meta?.status!=='READY')errors.push('ACTIVE_WITH_NON_READY_FEED');
if(errors.length){console.error(JSON.stringify({ok:false,errors},null,2));process.exit(1)}
console.log(JSON.stringify({ok:true,opportunities:x.opportunities.length,status:x.meta?.status||null,contract:'TEP-SUREBET-1.2'}));
